language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t manikkhosla/multi-docker -f ./client/Dockerfile.dev ./client  

script:
  - docker run -e CI=true manikkhosla/multi-docker npm test

after_success:
  - docker build -t manikkhosla/docker-client  ./client
  - docker build -t manikkhosla/docker-router  ./nginx
  - docker build -t manikkhosla/docker-server  ./server
  - docker build -t manikkhosla/docker-worker  ./worker
  # Push Prod images To Docker Hub
  - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
  - docker push manikkhosla/docker-client
  - docker push manikkhosla/docker-router 
  - docker push manikkhosla/docker-server 
  - docker push manikkhosla/docker-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-254471492897"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"